@base_url=http://127.0.0.1:5000

# **Customers Routes**

### Customers - Get customers
GET {{base_url}}/customers

### GET - a single customer by id
GET {{base_url}}/customers/1

### POST - Create a new customer
POST {{base_url}}/customers
Content-Type: application/json

{"name": "Alice", "address": "123 Main St", "phone": "555-1234"}

### PUT - update a user by id
PUT {{base_url}}/customers/1
Content-Type: application/json

{"name": "Brian"}

### DELETE - a user by id
DELETE {{base_url}}/customers/1

# **Subscriptions Routes**

### GET - subs
GET {{base_url}}/subscriptions

### GET - sub by id
GET {{base_url}}/subscriptions/1

### PUT - update sub by id
PUT {{base_url}}/subscriptions/1
Content-Type: application/json

{
    "end_date": "2025-07-31"
}

### Subscribe user to a publication
POST {{base_url}}/subscriptions/subscribe
Content-Type: application/json

{
  "customer_id": 1,
  "publication_id": 2
}

### Unsubscribe user from a publication (with at least 1 week notice)
POST {{base_url}}/subscriptions/unsubscribe
Content-Type: application/json

{
  "customer_id": 1,
  "publication_id": 2
}

### DELETE - sub by id
DELETE {{base_url}}/subscriptions/1

# **Publication Routes**

### GET - Get all publications
GET {{base_url}}/publications

### GET - Get a single publication by ID
GET {{base_url}}/publications/1

### POST - Create a new publication
POST {{base_url}}/publications
Content-Type: application/json

{
  "title": "Tech Times",
  "type": "newspaper"
}

### second publication
POST {{base_url}}/publications
Content-Type: application/json

{
  "title": "Good Times",
  "type": "magazine"
}

### PUT - Update publication by ID
PUT {{base_url}}/publications/1
Content-Type: application/json

{
  "title": "Tech Daily"
}

### DELETE - Delete publication by ID
DELETE {{base_url}}/publications/2


# **Carrier Routes**
### POST - Create a new carrier
POST {{base_url}}/carriers
Content-Type: application/json

{
    "name": "Jane Doe",
    "vehicle_type": "Truck",
    "vehicle_id": "DB1234",
    "phone": "122-456-7890",
    "is_active": true,
    "latitude": -122.4195,
    "longitude": 37.7750
}

### GET - all carriers
GET {{base_url}}/carriers

### GET -  a specific carrier
GET {{base_url}}/carriers/2

### PUT - Update a carrier
PUT {{base_url}}/carriers/1
Content-Type: application/json

{
    "latitude": -122.4195,
    "longitude": 37.7750
}

# {
#     "name": "John Doe Updated",
#     "vehicle_type": "Truck",
#     "vehicle_id": "XY1234",
#     "phone": "555-555-5555",
#     "is_active": false
# }

### Activate Carrier
PUT {{base_url}}/carriers/1/activate

### Deactivate carrier
PUT {{base_url}}/carriers/1/deactivate

### Delete a carrier
DELETE {{base_url}}/carriers/1


# **Delivery Routes**

### POST - Create Delivery Assignment
POST {{base_url}}/deliveries
Content-Type: application/json

{
    "date": "2025-07-22",
    "location_ids": [2],
    "publication_ids": [1]
}

# {
#     "delivery_person_id": 1,
#     "date": "2025-07-21",
#     "location_ids": [1],
#     "publication_ids": [1]
# }
### create assignment 2
POST {{base_url}}/deliveries
Content-Type: application/json

{
    "delivery_person_id": 1,
    "date": "2025-07-21",
    "location_ids": [2],
    "publication_ids": [2]
}


### GET - all Delivery Assignments
GET {{base_url}}/deliveries

### GET
GET {{base_url}}/deliveries?delivery_person_id=1

###
GET {{base_url}}/deliveries?date=2025-07-21

###
GET {{base_url}}/deliveries?delivery_person_id=1&date=2025-07-21

### GET - a Specific Delivery Assignment
GET {{base_url}}/deliveries/5

### PUT - update Delivery Assignment
PUT {{base_url}}/deliveries/1
Content-Type: application/json

{
    "location_ids": [1]
}

### GET - deliveries for a specific date
GET {{base_url}}/deliveries/daily/2025-07-22

###
GET {{base_url}}/deliveries/daily/2025-07-22?delivery_person_id=1

### GET - deliveries for a specific person
GET {{base_url}}/deliveries/person/1

### POST - Assign deliveries
POST {{base_url}}/deliveries/assign/2025-07-22

###
POST {{base_url}}/deliveries/assign/2025-07-21?is_active=true


### DELETE - delete Delivery Assignment
DELETE {{base_url}}/deliveries/1


# **Location routes**
### POST - Create a new location
POST {{base_url}}/locations
Content-Type: application/json

{
    "latitude": 37.7749,
    "longitude": -122.4194,
    "address": "123 Main St, San Francisco, CA",
    "city": "San Francisco",
    "postal_code": "94103"
}

### GET - get all locations
GET {{base_url}}/locations

### GET - get location by id
GET {{base_url}}/locations/1

### PUT - update location
PUT {{base_url}}/locations/1
Content-Type: application/json

{
    "address": "456 Elm St, San Francisco, CA",
    "city": "San Francisco",
    "postal_code": "94105"
}

### DELETE - location
DELETE {{base_url}}/locations/1

