"""Fix backref conflict

Revision ID: 037f31e54337
Revises: f2170e7dfa10
Create Date: 2025-07-21 21:55:42.010349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037f31e54337'
down_revision = 'f2170e7dfa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_id'))
        batch_op.drop_index(batch_op.f('ix_publication_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_start_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###
