"""update_user_model

Revision ID: 75378c94a7cc
Revises: 95f71848417a
Create Date: 2025-07-26 21:07:10.069781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75378c94a7cc'
down_revision = '95f71848417a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
