"""Add subscription model for users

Revision ID: 75797cc98fec
Revises: c373849e6d21
Create Date: 2025-07-22 15:49:33.616930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75797cc98fec'
down_revision = 'c373849e6d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_delivery_persons')
    with op.batch_alter_table('delivery_persons', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('requested_change_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('change_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('change_approved')
        batch_op.drop_column('requested_change_date')
        batch_op.drop_column('status')

    with op.batch_alter_table('delivery_persons', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('_alembic_tmp_delivery_persons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vehicle_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('hire_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
