"""Added location relationship in DeliveryAssignment

Revision ID: 7c4dc2ad08ee
Revises: 
Create Date: 2025-07-22 13:53:48.323407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4dc2ad08ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_delivery_assignments_location', 'locations', ['location_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
