"""Updated Subscription model with relationships and end_date, also add DeliveryAssignmentPubliction model

Revision ID: f2170e7dfa10
Revises: d7b7c4612a3d
Create Date: 2025-07-21 21:50:05.414069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2170e7dfa10'
down_revision = 'd7b7c4612a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_assignment', schema=None) as batch_op:
        batch_op.drop_column('publications')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index('ix_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_publication_id', ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_start_date'))
        batch_op.drop_index('ix_publication_id')
        batch_op.drop_index('ix_customer_id')

    with op.batch_alter_table('delivery_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publications', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
